version: "3.9"

services:
  app:
    build:
      context: ./app
      dockerfile: ./app/Dockerfile
    volumes:
      - ../src/:/app

  web:
    build:
      context: ./web
      dockerfile: ./web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ../src/:/app

  db:
    build:
      context: ./db
      dockerfile: ./db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
